version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ENV=local
  db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: p_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/models
volumes:
  pgdata: {}
